PURCHASE_ACTIONS_GAMEOBJECT = "purchase_actions"
PURCHASE_ACTIONS_RECEIVER = PURCHASE_ACTIONS_GAMEOBJECT.."#purchase_actions"

PURCHASE_ACTIONS_CONFIRM_TWO_STEP_PURCHASE = "confirm_two_step_purchase"
PURCHASE_ACTIONS_CANCEL_TWO_STEP_PURCHASE = "cancel_two_step_purchase"
PURCHASE_ACTIONS_GET_PURCHASE = "get_purchase"
PURCHASE_ACTIONS_PAID_ONLY = "paid_only"

PURCHASE_ACTIONS_SET_RECEIVER_MESSAGE_ID = "purchase_actions_set_receiver_message_id"
PURCHASE_ACTIONS_BUTTON_PRESSED = "purchase_actions_button_pressed"
